// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "mtxClient.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::com::twitter::service::snowflake::gen;

class mtxClientHandler : virtual public mtxClientIf {
 public:
  mtxClientHandler() {
    // Your initialization goes here
  }

  int64_t getUniqueId(const std::string& key) {
    // Your implementation goes here
    printf("getUniqueId\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<mtxClientHandler> handler(new mtxClientHandler());
  ::std::shared_ptr<TProcessor> processor(new mtxClientProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

